title: Fatima A. Pardo Avila 
email: fpardo at stanford dot edu
description: >- # this means to ignore newlines until "baseurl:"
  I am using this website as a playground to explore my interests and improve my skillset.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "fatipardo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fatipardo

# Build settings
theme: jekyll-theme-cayman
